name: Build & Deploy
env:
  IMAGE_TAG_BACKEND: ghcr.io/fabian416/zk-drop/frontend

  IMAGE_VERSION: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
  NEXT_PUBLIC_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx Install
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./zk-front/
          file: ./zk-front/Dockerfile
          push: true
          tags: ${{env.IMAGE_TAG_BACKEND}}:${{env.IMAGE_VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args:
            NEXT_PUBLIC_ENVIRONMENT=${{ env.NEXT_PUBLIC_ENVIRONMENT }}